### PR TITLE
Graph DFS for total solutions of n-queen

### PR DESCRIPTION
**Pull request by dakshgupta2002**
A classic n-queen problem solved to print the total number of solutions for a given size of chessboard.

This Pull Request is under Hacktoberfest 2022.
Happy Hacking! :)

### CODE REVIEW

**Comment by pragmatist-strategist** [comment]
Just one advice: Never commit .exe file becoz jo bhi system pe run kr rha hoga he'll compile it as per his needs. Also, .exe will increase the size of the file. Baaki code seems perfect. Shall I proceed with the merge?

**Comment by dakshgupta2002** [comment]
Ill remove the .exe file right away

**Comment by dakshgupta2002** [comment]
Okay, it is removed!
Thank you for pointing it out :)

**Comment by pragmatist-strategist** [comment]
Cool
Proceeding with the merge !

**Pull request merged**
